[rpc]
base_url = "127.0.0.1"
main_port = 5005
cron_port = 5006

[database]
user = "postgres"
password = "postgres"
database_entrypoint = "mydatabase"
blob_storage_path = "/home/othi/.vps/data"

[cloudflare]
record_id = ""
zone_id = ""
api_token = ""
email = ""
